models/ArticleItem.php
<?php

namespace sycms\models;

use Yii;
use syuserman\models\User;

/**
 * This is the model class for table "article_item".
 *
 * @property integer $id
 * @property integer $article_category_id
 * @property string $title
 * @property string $subtitle
 * @property string $image
 * @property string $short_text
 * @property string $text
 * @property string $slug
 * @property integer $not_publish
 * @property string $keywords
 * @property string $description
 * @property string $created_at
 * @property integer $user_created
 * @property string $updated_at
 * @property integer $user_updated
 *
 * @property ArticleImage[] $articleImages
 * @property ArticleCategory $articleCategory
 * @property User $userCreated
 * @property User $userUpdated
 * @property LinkItem[] $linkItems
 */
class ArticleItem extends \sybase\SybaseModel
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'article_item';
    }
        

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['article_category_id', 'title', 'short_text', 'text', 'slug'], 'required'],
            [['article_category_id', 'not_publish', 'user_created', 'user_updated'], 'integer'],
            [['short_text', 'text', 'keywords', 'description'], 'string'],
            [['created_at', 'updated_at'], 'safe'],
            [['title', 'subtitle', 'image', 'slug'], 'string', 'max' => 128],
            [['slug'], 'unique'],
            [['article_category_id'], 'exist', 'skipOnError' => true, 'targetClass' => ArticleCategory::className(), 'targetAttribute' => ['article_category_id' => 'id']],
            [['user_created'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_created' => 'id']],
            [['user_updated'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_updated' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'article_category_id' => 'Article Category ID',
            'title' => 'Judul',
            'subtitle' => 'Sub Judul',
            'image' => 'Image',
            'short_text' => 'Text Singkat',
            'text' => 'Text',
            'slug' => 'Slug',
            'not_publish' => 'Not Publish',
            'keywords' => 'Kata Kunci',
            'description' => 'Deskripsi',
            'created_at' => 'Created At',
            'user_created' => 'User Created',
            'updated_at' => 'Updated At',
            'user_updated' => 'User Updated',
        ];
    }
    
    public static function getItemByCategory($categorySlug, $limit = 4) {
        
        return ArticleItem::find()
                ->joinWith([
                    'articleCategory',
                ])
                ->andWhere(['article_category.slug' => $categorySlug])
                ->andWhere(['article_item.not_publish' => 0])
                ->limit($limit)
                ->orderBy('article_item.id DESC')
                ->asArray()->all();
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticleImages()
    {
        return $this->hasMany(ArticleImage::className(), ['article_item_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticleCategory()
    {
        return $this->hasOne(ArticleCategory::className(), ['id' => 'article_category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserCreated()
    {
        return $this->hasOne(User::className(), ['id' => 'user_created']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserUpdated()
    {
        return $this->hasOne(User::className(), ['id' => 'user_updated']);
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLinkItems()
    {
        return $this->hasMany(LinkItem::className(), ['article_item_id' => 'id']);
    }
}

controllers/ArticleItemController.php
<?php

namespace sycms\controllers;

use Yii;
use sycms\models\ArticleItem;
use sycms\models\search\ArticleItemSearch;
use sycms\models\ArticleImage;
use sycomponent\Tools;
use sybase\SybaseController;
use yii\helpers\Inflector;
use yii\helpers\StringHelper;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use yii\widgets\ActiveForm;


/**
 * ArticleItemController implements the CRUD actions for ArticleItem model.
 */
class ArticleItemController extends SybaseController
{
    public function behaviors()
    {
        return array_merge(
            $this->getAccess(),
            [                
                'verbs' => [
                    'class' => VerbFilter::className(),
                    'actions' => [
                        'delete' => ['post'],
                    ],
                ],
            ]);
    }

    /**
     * Lists all ArticleItem models.
     * @return mixed
     */
    public function actionIndex($cid)
    {
        if (Yii::$app->request->isAjax) {
            $this->layout = 'ajax';
        }
        
        $searchModel = new ArticleItemSearch();
        $searchModel->article_category_id = $cid;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ArticleItem model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        if (Yii::$app->request->isAjax) {
            $this->layout = 'ajax';
        }
        
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ArticleItem model.
     * If creation is successful, the browser will be redirected to the 'update' page.
     * @return mixed
     */
    public function actionCreate($save = null, $cid)
    {
        if (Yii::$app->request->isAjax) {
            $this->layout = 'ajax';
        }
        
        $render = 'create';
        
        $model = new ArticleItem();
        $model->article_category_id = $cid;

        if ($model->load(Yii::$app->request->post())) {
        
            if (empty($save)) {
                
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            } else {
                
                $model->slug = StringHelper::truncate(Inflector::slug($model->title), 64, '');
                
                $model->image = Tools::uploadFile('/img/article_item/', $model, 'image', 'slug');
            
                if ($model->save()) {
                
                    Yii::$app->session->setFlash('status', 'success');
                    Yii::$app->session->setFlash('message1', 'Tambah Data Sukses');
                    Yii::$app->session->setFlash('message2', 'Proses tambah data sukses. Data telah berhasil disimpan.');

                    $render = 'update';
                } else {
                
                    $model->setIsNewRecord(true);

                    Yii::$app->session->setFlash('status', 'danger');
                    Yii::$app->session->setFlash('message1', 'Tambah Data Gagal');
                    Yii::$app->session->setFlash('message2', 'Proses tambah data gagal. Data gagal disimpan.');                
                }                                
            }
        }
        
        return $this->render($render, [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ArticleItem model.
     * If update is successful, the browser will be redirected to the 'update' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id, $save = null)
    {
        if (Yii::$app->request->isAjax) {
            $this->layout = 'ajax';
        }
        
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
        
            if (empty($save)) {
                
                Yii::$app->response->format = Response::FORMAT_JSON;
                return ActiveForm::validate($model);
            } else {
                
                $model->slug = StringHelper::truncate(Inflector::slug($model->title), 64, '');
                
                if (($model->image = Tools::uploadFile('/img/article_item/', $model, 'image', 'slug'))) {
                
                } else {
                    $model->image = $model->oldAttributes['image'];
                }
            
                if ($model->save()) {
                
                    Yii::$app->session->setFlash('status', 'success');
                    Yii::$app->session->setFlash('message1', 'Update Sukses');
                    Yii::$app->session->setFlash('message2', 'Proses update sukses. Data telah berhasil disimpan.');
                } else {
                
                    Yii::$app->session->setFlash('status', 'danger');
                    Yii::$app->session->setFlash('message1', 'Update Gagal');
                    Yii::$app->session->setFlash('message2', 'Proses update gagal. Data gagal disimpan.');
                }
            }
        }
        
        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ArticleItem model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if (($model = $this->findModel($id)) !== false) {
            
            $flag = false;
            $error = '';
            
            try {
                $flag = $model->delete();
            } catch (yii\db\Exception $exc) {
                $error = Yii::$app->params['errMysql'][$exc->errorInfo[1]];
            }
        }
        
        if ($flag) {
        
            Yii::$app->session->setFlash('status', 'success');
            Yii::$app->session->setFlash('message1', 'Delete Sukses');
            Yii::$app->session->setFlash('message2', 'Proses delete sukses. Data telah berhasil dihapus.');            
        } else {
        
            Yii::$app->session->setFlash('status', 'danger');
            Yii::$app->session->setFlash('message1', 'Delete Gagal');
            Yii::$app->session->setFlash('message2', 'Proses delete gagal. Data gagal dihapus.' . $error);
        }

        $return = [];
        
        $return['url'] = Yii::$app->urlManager->createUrl([Yii::$app->params['sycmsPath'] . '/article-item/index', 'cid' => $model->article_category_id]);
        
        Yii::$app->response->format = Response::FORMAT_JSON;                        
        return $return;
    }
    
    public function actionImage($id) {

        if (Yii::$app->request->isAjax) {
            $this->layout = 'ajax';
        }

        $model = $this->findModel($id);

        return $this->render('image', [
            'model' => $model,
            'modelArticleImage' => new ArticleImage(),
        ]);
    }

    public function actionSaveImage($id) {

        if (!empty($post = Yii::$app->request->post())) {

            $transaction = Yii::$app->db->beginTransaction();
            $flag = false;

            $modelArticleImage = new ArticleImage();
            $modelArticleImage->load($post);

            $modelArticleImage->article_item_id = $id;
            $modelArticleImage->image = Tools::uploadFile('/img/article_image/', $modelArticleImage, 'image', 'article_item_id');

            $flag = $modelArticleImage->save();

            if ($flag) {
                $transaction->commit();
            } else {
                $transaction->rollBack();
            }
        }

        Yii::$app->response->format = Response::FORMAT_JSON;
        return [];
    }

    public function actionDeleteImage() {

        $flag = false;

        if (!empty($post = Yii::$app->request->post())) {

            $flag = ArticleImage::findOne($post['id'])->delete();
        }

        $return = [];

        if ($flag) {
            $return['success'] = true;
        }

        Yii::$app->response->format = Response::FORMAT_JSON;
        return $return;
    }

    /**
     * Finds the ArticleItem model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ArticleItem the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ArticleItem::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/article-item/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use dosamigos\ckeditor\CKEditor;
use kartik\file\FileInput;
use sycomponent\AjaxRequest;
use sycomponent\NotificationDialog;

/* @var $this yii\web\View */
/* @var $model sycms\models\ArticleItem */
/* @var $form yii\widgets\ActiveForm */

$ajaxRequest = new AjaxRequest([
    'modelClass' => 'ArticleItem',
]);

$ajaxRequest->form();

$status = Yii::$app->session->getFlash('status');
$message1 = Yii::$app->session->getFlash('message1');
$message2 = Yii::$app->session->getFlash('message2');

if ($status !== null) : 
    $notif = new NotificationDialog([
        'status' => $status,
        'message1' => $message1,
        'message2' => $message2,
    ]);

    $notif->theScript();
    echo $notif->renderDialog();

endif; ?>

<?= $ajaxRequest->component() ?>

<div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
        <div class="x_panel">
            <div class="article-item-form">

                <?php $form = ActiveForm::begin([
                        'id' => 'article-item-form',
                        'action' => $model->isNewRecord ? ['create', 'cid' => $model->article_category_id] : ['update', 'id' => $model->id],
                        'options' => [

                        ],
                        'fieldConfig' => [
                            'parts' => [
                                '{inputClass}' => 'col-lg-12'
                            ],
                            'template' => '<div class="row">'
                                            . '<div class="col-lg-3">'
                                                . '{label}'
                                            . '</div>'
                                            . '<div class="col-lg-6">'
                                                . '<div class="{inputClass}">'
                                                    . '{input}'
                                                . '</div>'
                                            . '</div>'
                                            . '<div class="col-lg-3">'
                                                . '{error}'
                                            . '</div>'
                                        . '</div>', 
                        ]
                ]); ?>
                    
                    <div class="x_title">
                    
                        <div class="form-group">
                            <div class="row">
                                <div class="col-lg-6">
                                    <?php
                                    if (!$model->isNewRecord) {
                                        echo Html::a('<i class="fa fa-upload"></i>&nbsp;&nbsp;&nbsp;' . 'Create', ['create', 'cid' => $model->article_category_id], ['class' => 'btn btn-success']);
                                        echo Html::a('<i class="fa fa-file-image-o"></i>&nbsp;&nbsp;&nbsp;' . 'Gambar', ['image', 'id' => $model->id], ['class' => 'btn btn-success']); 
                                    } ?>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                
                    <div class="x_content">

                        <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

                        <?= $form->field($model, 'subtitle')->textInput(['maxlength' => true]) ?>

                        <?= $form->field($model, 'image')->widget(FileInput::classname(), [
                            'options' => [
                                'accept' => 'image/*'
                            ],
                            'pluginOptions' => [
                                'initialPreview' => [
                                    Html::img(Yii::getAlias('@uploadsUrl') . $model->thumb('/img/article_item/', 'image', 200, 200), ['class'=>'file-preview-image']),
                                ],
                                'showRemove' => false,
                                'showUpload' => false,
                            ]
                        ]); ?>

                        <?= $form->field($model, 'short_text', [                        
                            'template' => '<div class="row">
                                                <div class="col-lg-3">
                                                    {label}
                                                </div>
                                                <div class="col-lg-9">
                                                    <div class="{inputClass}">
                                                        {input}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    {error}
                                                </div>
                                            </div>',
                        ])->textarea(['rows' => 6]) ?>

                        <?= $form->field($model, 'text', [                        
                            'template' => '<div class="row">
                                                <div class="col-lg-3">
                                                    {label}
                                                </div>
                                                <div class="col-lg-9">
                                                    <div class="{inputClass}">
                                                        {input}
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    {error}
                                                </div>
                                            </div>',
                        ])->widget(CKEditor::className(), [
                            'options' => ['rows' => 6],
                            'preset' => 'full',
                            'clientOptions' => [
                                'extraPlugins' => 'codesnippet,iframe',
                                'allowedContent' => true,
                            ],
                        ]) ?>

                        <?= $form->field($model, 'not_publish')->checkbox(['value' => true], false) ?>
                        
                        <?php
                        if (!$model->isNewRecord) {                            
                            echo $form->field($model, 'slug')->textInput(['maxlength' => true]);
                        } ?>
                        
                        <br>
                        <h4><label class="form-label">SEO</label></h4>

                        <?= $form->field($model, 'keywords')->textarea(['rows' => 3]) ?>

                        <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

                        <div class="form-group">
                            <div class="row">
                                <div class="col-lg-3"></div>
                                <div class="col-lg-6">
                                    <?php
                                    $icon = '<i class="fa fa-floppy-o"></i>&nbsp;&nbsp;&nbsp;';
                                    echo Html::submitButton($model->isNewRecord ? $icon . 'Save' : $icon . 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']);
                                    echo '&nbsp;&nbsp;&nbsp;';
                                    echo Html::a('<i class="fa fa-rotate-left"></i>&nbsp;&nbsp;&nbsp;Cancel', ['index', 'cid' => $model->article_category_id], ['class' => 'btn btn-default']); ?>
                                </div>
                            </div>
                        </div>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>
    </div>
    <div class="col-sm-2"></div>
</div><!-- /.row -->

<?php

$this->registerCssFile($this->params['assetCommon']->baseUrl . '/plugins/iCheck/all.css', ['depends' => 'yii\web\YiiAsset']);
 
$this->registerJsFile($this->params['assetCommon']->baseUrl . '/plugins/iCheck/icheck.min.js', ['depends' => 'yii\web\YiiAsset']);

$jscript = '
    
';

$this->registerJs($jscript . Yii::$app->params['checkbox-radio-script']()); ?>

views/article-item/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model sycms\models\search\ArticleItemSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="article-item-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'article_category_id') ?>

    <?= $form->field($model, 'title') ?>

    <?= $form->field($model, 'subtitle') ?>

    <?= $form->field($model, 'image') ?>

    <?php // echo $form->field($model, 'short_text') ?>

    <?php // echo $form->field($model, 'text') ?>

    <?php // echo $form->field($model, 'slug') ?>

    <?php // echo $form->field($model, 'not_publish') ?>

    <?php // echo $form->field($model, 'keywords') ?>

    <?php // echo $form->field($model, 'description') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'user_created') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'user_updated') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/article-item/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model sycms\models\ArticleItem */

$this->title = 'Create Artikel ' . $model->articleCategory->title;
$this->params['breadcrumbs'][] = ['label' => 'Kategori Artikel', 'url' => ['article-category/index']];
$this->params['breadcrumbs'][] = ['label' => $model->articleCategory->title, 'url' => ['index', 'cid' => $model->article_category_id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="article-item-create">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/article-item/image.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use kartik\file\FileInput;
use sycomponent\AjaxRequest;
use sycomponent\NotificationDialog;

/* @var $this yii\web\View */
/* @var $model sycms\models\Product */

$ajaxRequest = new AjaxRequest([
    'modelClass' => 'ArticleItem',
]);

$ajaxRequest->form();

$status = Yii::$app->session->getFlash('status');
$message1 = Yii::$app->session->getFlash('message1');
$message2 = Yii::$app->session->getFlash('message2');

if ($status !== null) : 
    $notif = new NotificationDialog([
        'status' => $status,
        'message1' => $message1,
        'message2' => $message2,
    ]);

    $notif->theScript();
    echo $notif->renderDialog();

endif;

$this->title = 'Galeri Artikel: ' . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Artikel', 'url' => ['index', 'cid' => $model->article_category_id]];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['update', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Galeri';
?>

<?= $ajaxRequest->component() ?>

<div class="article-image">

    <?php $form = ActiveForm::begin([
        'id' => 'article-item-form',
        'action' => ['image', 'id' => $model->id],
        'options' => [

        ],
    ]); ?>
    
        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
                <div class="x_panel">                    
                    <div class="x_content">
                        <div class="row">
                            
                            <?php
                            if (!empty($model->articleImages)):

                                foreach ($model->articleImages as $articleImage): ?>

                                    <div class="col-sm-3 text-center" style="margin-bottom: 20px">
                                        <?= Html::img(Yii::getAlias('@uploadsUrl') . $articleImage->thumb('/img/article_image/', 'image', 250, 250), ['class'=>'img-thumbnail file-preview-image']) ?>
                                        <div class="clearfix" style="margin-top: 5px"></div>
                                        <?= Html::a('<i class="fa fa-trash"></i> Delete', ['article-item/delete-image'], ['class' => 'btn btn-danger btn-xs delete-image']) ?>
                                        <?= Html::hiddenInput('article-item_image-id', $articleImage['id'], ['class' => 'article-item_image-id']) ?>
                                    </div>


                                <?php
                                endforeach;
                            endif; ?>
                                
                        </div>
                            
                        <div class="clearfix" style="margin-top: 20px"></div>

                        <div class="article-item-form">

                            <?= $form->field($modelArticleImage, 'image')->widget(FileInput::classname(), [
                                'options' => [
                                    'accept' => 'image/*',
                                    'multiple' => true,
                                ],
                                'pluginOptions' => [
                                    'showRemove' => true,
                                    'showUpload' => true,
                                    'uploadUrl' => Url::to(['article-item/save-image', 'id' => $model->id]),
                                ]
                            ]); ?>

                            <div class="form-group">                            
                                <?= Html::a('<i class="fa fa-rotate-left"></i>&nbsp;&nbsp;&nbsp;Cancel', ['update', 'id' => $model->id], ['class' => 'btn btn-default']); ?>                                
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>            
    
    <?php ActiveForm::end(); ?>

</div>

<?php
$jscript = '
    $(".delete-image").on("click", function() {
    
        var thisObj = $(this);
    
        $.ajax({
            cache: false,
            type: "POST",
            data: {
                "id": thisObj.parent().find(".article-item_image-id").val()
            },
            url: thisObj.attr("href"),
            beforeSend: function(xhr) {
                $(".overlay").show();
                $(".loading-img").show();
            },
            success: function(response) {                

                if (response.success) {
                    
                    thisObj.parent().fadeOut(180, function() {
                        $(this).remove();
                    });
                }
                
                $(".overlay").hide();
                $(".loading-img").hide();                
            },
            error: function (xhr, ajaxOptions, thrownError) {                     
                console.log(xhr);

                $(".overlay").hide();
                $(".loading-img").hide();

                $(".error-overlay").find(".error-number").html(xhr.status);
                $(".error-overlay").find(".error-message").html(xhr.responseText);
                $(".error-overlay").show();

                setTimeout(function() {                    
                    $(".error-overlay").hide();
                }, 1000);
            }
        });

        return false;
    });
';

$this->registerJs($jscript); ?>

views/article-item/update.php
<?php

use yii\helpers\Html;
use yii\helpers\StringHelper;

/* @var $this yii\web\View */
/* @var $model sycms\models\ArticleItem */

$this->title = 'Update Artikel: ' . ' ' . StringHelper::truncateWords($model->title, 3);
$this->params['breadcrumbs'][] = ['label' => 'Kategori Artikel', 'url' => ['article-category/index']];
$this->params['breadcrumbs'][] = ['label' => $model->articleCategory->title, 'url' => ['index', 'cid' => $model->article_category_id]];
$this->params['breadcrumbs'][] = ['label' => StringHelper::truncateWords($model->title, 3), 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="article-item-update">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>